version: "3.8"
services: 
  ws_service:
    env_file: .env
    build: ./service
    restart: always
    ports:
      - "80:80"
    depends_on:
      - redis
    volumes:
    - map_snapshots:/var/www/html/pictures

  worker:
    env_file: .env
    build: ./worker
    restart: always
    scale: 3
    depends_on:
      - redis
    volumes:
    - map_snapshots:/var/www/html/pictures

  redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"

    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  map_snapshots:
    external: false